#!/bin/sh

### BEGIN INIT INFO
# Provides:          liotad
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts liota daemon
### END INIT INFO

DIR=/etc/liota/packages    
DAEMON=$DIR/liotad.py
DAEMON_NAME=liotad

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

#Get lsb functions
. /lib/lsb/init-functions

check_init() {
    # see also init_is_upstart in /lib/lsb/init-functions (which isn't available in Ubuntu 12.04, or we'd use it directly)
    if [ -x /sbin/initctl ] && /sbin/initctl version 2>/dev/null | grep -q upstart; then
        log_failure_msg "$DAEMON_NAME is managed via upstart, try using service $DAEMON_NAME $1"
        exit 1
    fi
}

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
    log_end_msg $?
}

case "$1" in

    start|stop)
        check_init
        do_${1}
        ;;

    restart|reload|force-reload)
        check_init
        do_stop
        do_start
        ;;

    status)
        check_init
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
